version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">10"
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
